package com.forestry.aireviewer.model;

public enum FindingType {
    INTERNAL_CONTRADICTION,
    MISSING_EVIDENCE,
    BIODIVERSITY_RISK,
    ENVIRONMENTAL_IMPACT,
    UNSUPPORTED_CONCLUSION,
    VAGUE_LANGUAGE,
    WEAK_MITIGATION,
    POSSIBLE_REGULATORY_CONCERN
}
